name: countly_flutter
description: Countly is an innovative, real-time, open source mobile analytics and push notifications platform. It collects data from mobile devices, and visualizes this information to analyze mobile application usage and end-user behavior. There are two parts of Countly, the server that collects and analyzes data, and mobile SDK that sends this data. Both parts are open source with different licensing terms.
version: 20.04.0
homepage: https://support.count.ly/hc/en-us/articles/360037944212-Flutter

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: ly.count.dart.countly_flutter
    pluginClass: CountlyFlutterPlugin
