name: countly_flutter
description: Countly is an innovative, real-time, open source mobile analytics and push notifications platform.
version: 20.11.2
homepage: https://support.count.ly/hc/en-us/articles/360037944212-Flutter

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter_plugin_android_lifecycle: ^2.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: ly.count.dart.countly_flutter
        pluginClass: CountlyFlutterPlugin
      ios:
        pluginClass: CountlyFlutterPlugin

